### ISSUE TITLE
Update the PRYSM_BOOTSTRAP_NODE value

### ISSUE THREAD

**Issue by DaniSchenk** [lukso-network/network-docker-containers#13]
https://github.com/lukso-network/network-docker-containers/blob/146dac8004eaeef4c980342e7e3bbfb7973e7d15/.env.example#L28

`.env.example` sets a `PRYSM_BOOTSTRAP_NODE` that I cannot find in https://github.com/lukso-network/network-configs/blob/e65798127a8b1b92026f9284f08bd6046f96acc9/mainnet/prysm/prysm.yaml#L17 anymore. I seems it was remove by [e1a23eb](https://github.com/lukso-network/network-configs/commit/e1a23ebdd4fb44780a6bfa5dabb09aeb83ba3296) in August. 2023. I'll provide a PR if the value should be updated.

**Comment by mxmar** [comment]
@DaniSchenk, it has changed. We are now using [new envs](https://github.com/lukso-network/network-docker-containers/blob/c38556737d8929bab5983028b863acb9fa3a9961/.env.mainnet#L39). The Prysm ENR is changing with every run, but it points to the same IP, port, and node key (bootnode key). This has been confirmed by Prysmatic Labs.
The Lighthouse client has a `--disable-enr-auto-update` flag for this.
