### ISSUE TITLE
account-password and wallet-password should not have the same secret?

### ISSUE THREAD

**Issue by percenuage** [lukso-network/network-docker-containers#7]
From the docker-compose (`https://github.com/lukso-network/network-docker-containers/blob/main/docker-compose.yml`), during the `prysm_validator_import` (lines 107, 108), 2 secrets (account and wallet) have the same values. Is it normal or an error?

``` yaml
      accounts import
      --accept-terms-of-use
      --keys-dir=/keystore
      --wallet-dir=/keystore/prysm
      --wallet-password-file=/tmp/secrets/password.txt
      --account-password-file=/tmp/secrets/password.txt
```
I generated keystores and mnemonic from your CLI (https://github.com/lukso-network/tools-key-gen-cli). During the process, I enter a secret. I suppose this secret is the `wallet-password` from prysm, isn't it? If yes, what is the `account-password`? 

Thanks for your help.

**Comment by Wolmin** [comment]
Hi, thanks for the patience and our apologies for the late response. If you take a look at point 7) in our How to use section of the README (https://github.com/lukso-network/network-docker-containers#how-to-use), there is note that states the issue that you just mentioned. If this is something that you would like to change then feel free to edit your docker-compose file however you please :) the solution above, just as you stated, will simply use the same password for importing your keystores and creating a new wallet, so no issues there - I will close this issue in this case.
